[2021-03-17 11:13:10] WARNING root pid:6884 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 106, in rendered_content
    self.resolve_data(request)
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 92, in resolve_data
    self.resilve_json_data()
AttributeError: 'Response' object has no attribute 'resilve_json_data'

[2021-03-17 11:13:17] WARNING root pid:6884 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 106, in rendered_content
    self.resolve_data(request)
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 92, in resolve_data
    self.resilve_json_data()
AttributeError: 'Response' object has no attribute 'resilve_json_data'

[2021-03-17 11:13:32] WARNING root pid:6884 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 106, in rendered_content
    self.resolve_data(request)
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 92, in resolve_data
    self.resilve_json_data()
AttributeError: 'Response' object has no attribute 'resilve_json_data'

[2021-03-17 11:16:20] WARNING root pid:7233 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 39, in get_template
    return Template(self.env.get_template(template_name), self)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/templates/myadmin/user/edit.html", line 217, in <module>
    {% with select_list=data.role %}
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 459, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 893, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 122, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 229, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 157, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 136, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 89, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 82, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 51, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'with'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 161, in render
    template = self.resolve_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 171, in resolve_template
    return loader.select_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 45, in get_template
    raise new from exc
django.template.exceptions.TemplateSyntaxError: ("Encountered unknown tag 'with'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.",)

[2021-03-17 11:16:20] ERROR django.request pid:7233 exception.py:118 Internal Server Error: /myadmin/user/edit
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 39, in get_template
    return Template(self.env.get_template(template_name), self)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/templates/myadmin/user/edit.html", line 217, in <module>
    {% with select_list=data.role %}
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 459, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 893, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 122, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 229, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 157, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 136, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 89, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 82, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 51, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'with'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 161, in render
    template = self.resolve_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 171, in resolve_template
    return loader.select_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 45, in get_template
    raise new from exc
django.template.exceptions.TemplateSyntaxError: ("Encountered unknown tag 'with'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.",)
[2021-03-17 11:18:00] WARNING root pid:7233 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 39, in get_template
    return Template(self.env.get_template(template_name), self)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/templates/myadmin/role/edit.html", line 259, in <module>
    {% with resource_map_ids=data.resource_map_ids,model_resource=model_resource,select_list=data.resource_map_ids.get(name,[]),resource_name=name %}
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 459, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 893, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 122, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 229, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 157, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 122, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 187, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 157, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 122, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 200, in parse_if
    node.body = self.parse_statements(('name:elif', 'name:else',
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 157, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 136, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 89, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 82, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 51, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'with'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 161, in render
    template = self.resolve_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 171, in resolve_template
    return loader.select_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 45, in get_template
    raise new from exc
django.template.exceptions.TemplateSyntaxError: ("Encountered unknown tag 'with'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.",)

[2021-03-17 11:18:00] ERROR django.request pid:7233 exception.py:118 Internal Server Error: /myadmin/role/edit
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 39, in get_template
    return Template(self.env.get_template(template_name), self)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/templates/myadmin/role/edit.html", line 259, in <module>
    {% with resource_map_ids=data.resource_map_ids,model_resource=model_resource,select_list=data.resource_map_ids.get(name,[]),resource_name=name %}
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 459, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 893, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 122, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 229, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 157, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 122, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 187, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 157, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 122, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 200, in parse_if
    node.body = self.parse_statements(('name:elif', 'name:else',
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 157, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    rv = self.parse_statement()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 136, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 89, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 82, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/parser.py", line 51, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'with'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 161, in render
    template = self.resolve_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 171, in resolve_template
    return loader.select_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 45, in get_template
    raise new from exc
django.template.exceptions.TemplateSyntaxError: ("Encountered unknown tag 'with'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.",)
[2021-03-17 11:22:30] WARNING root pid:7353 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 126, in rendered_content
    return super(JsonResponse, self).rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/utils/__init__.py", line 91, in default
    return [m.to_dict() for m in obj]
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/utils/__init__.py", line 91, in <listcomp>
    return [m.to_dict() for m in obj]
AttributeError: 'int' object has no attribute 'to_dict'

[2021-03-17 11:23:37] WARNING root pid:7353 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 126, in rendered_content
    return super(JsonResponse, self).rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/utils/__init__.py", line 91, in default
    return [m.to_dict() for m in obj]
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/utils/__init__.py", line 91, in <listcomp>
    return [m.to_dict() for m in obj]
AttributeError: 'int' object has no attribute 'to_dict'

[2021-03-17 11:25:58] WARNING root pid:7353 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 126, in rendered_content
    return super(JsonResponse, self).rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/utils/__init__.py", line 91, in default
    return [m.to_dict() for m in obj]
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/utils/__init__.py", line 91, in <listcomp>
    return [m.to_dict() for m in obj]
AttributeError: 'int' object has no attribute 'to_dict'

[2021-03-17 11:37:13] WARNING root pid:7650 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 39, in get_template
    return Template(self.env.get_template(template_name), self)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/drf_yasg/templates/drf-yasg/redoc.html", line 1, in template
    {% load static %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'load'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/drf_yasg/renderers.py", line 75, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 45, in get_template
    raise new from exc
django.template.exceptions.TemplateSyntaxError: ("Encountered unknown tag 'load'.",)

[2021-03-17 11:37:13] ERROR django.request pid:7650 exception.py:118 Internal Server Error: /redoc
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 39, in get_template
    return Template(self.env.get_template(template_name), self)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/drf_yasg/templates/drf-yasg/redoc.html", line 1, in template
    {% load static %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'load'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/drf_yasg/renderers.py", line 75, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/jinja2.py", line 45, in get_template
    raise new from exc
django.template.exceptions.TemplateSyntaxError: ("Encountered unknown tag 'load'.",)
[2021-03-17 11:49:49] WARNING root pid:7979 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 109, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 161, in render
    template = self.resolve_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 171, in resolve_template
    return loader.select_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/base.py", line 539, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'set'. Did you forget to register or load this tag?

[2021-03-17 11:49:49] ERROR django.request pid:7979 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 109, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 161, in render
    template = self.resolve_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 171, in resolve_template
    return loader.select_template(template_names)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/base.py", line 539, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'set'. Did you forget to register or load this tag?
[2021-03-17 12:55:41] WARNING root pid:10007 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 12:55:41] ERROR django.request pid:10007 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
[2021-03-17 12:56:41] WARNING root pid:10007 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 12:56:41] ERROR django.request pid:10007 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
[2021-03-17 12:58:39] WARNING root pid:10007 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 12:58:39] ERROR django.request pid:10007 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
[2021-03-17 13:00:54] WARNING root pid:10087 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 13:00:54] ERROR django.request pid:10087 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
[2021-03-17 13:01:15] WARNING root pid:10114 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 13:01:15] ERROR django.request pid:10114 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
[2021-03-17 13:01:18] WARNING root pid:10114 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 13:01:18] ERROR django.request pid:10114 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
[2021-03-17 13:01:33] WARNING root pid:10114 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 13:01:33] ERROR django.request pid:10114 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
[2021-03-17 13:07:21] WARNING root pid:10237 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 13:07:21] ERROR django.request pid:10237 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
[2021-03-17 13:07:34] WARNING root pid:10237 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 13:07:34] ERROR django.request pid:10237 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
[2021-03-17 13:11:30] WARNING root pid:10288 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 13:11:30] ERROR django.request pid:10288 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
[2021-03-17 13:12:46] WARNING root pid:10288 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 13:12:46] ERROR django.request pid:10288 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
[2021-03-17 13:14:26] WARNING root pid:10288 middleware.py:81 Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable

[2021-03-17 13:14:26] ERROR django.request pid:10288 exception.py:118 Internal Server Error: /myadmin/login
Traceback (most recent call last):
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/xzr/Desktop/pipy/djmyframework/djmyframework/framework/response.py", line 108, in rendered_content
    return super(Response, self).rendered_content
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 725, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 681, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 414, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/xzr/.virtualenvs/djmyframework/lib/python3.7/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
